### ISSUE TITLE
Select all markdown text in advance when user click its element to copy it.

### ISSUE THREAD

**Issue by nk18chi** [dorokei/unfurler#2]
When users try to copy the markdown text, they need to select the whole text. I think you could reduce one step if this app automatically selects all markdown text when users click its box. I hope the user experience will be better.

**Comment by dorokei** [comment]
@nk18chi 
I'm gonna implement a copy button. I think this function may cover your request.
Thank you for your advice!

**Comment by dorokei** [comment]
It's done.
https://github.com/dorokei/unfurler/commit/4879c5d685f378ba37883e97669419e4608b479d
